# Authentication configuration for Klu Chatbot

# Token-based authentication settings
token:
  secret: YOUR_SECRET_KEY
  expiration: 3600

# OAuth settings (if applicable)
oauth:
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  redirect_uri: YOUR_REDIRECT_URI
  scopes: ['read', 'write']