# Secrets configuration for Klu Chatbot

# Database secrets
database:
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  name: <%= ENV['DATABASE_NAME'] %>

# API secrets
api:
  key: <%= ENV['API_KEY'] %>
  secret: <%= ENV['API_SECRET'] %>

# Other secrets (if applicable)
other:
  secret_key: <%= ENV['OTHER_SECRET_KEY'] %>
